config/routes.rb
Rails.application.routes.draw do
  
  root 'lookup#index'
  post '/' => 'lookup#index'
  get 'ip/' => 'lookup#ip'
  post 'ip/' => 'lookup#ip'
  get '/traceroute/:uuid' => 'lookup#index'
  post '/check/:uuid' => 'lookup#check'
  get '/check/:uuid' => 'lookup#check'

end

app/models/hop.rb
class Hop < ActiveRecord::Base
  belongs_to :traceroute
end

app/models/traceroute.rb
class Traceroute < ActiveRecord::Base
  include Ripe
  include Ipv4
  has_many :hops, -> { order "no ASC" }, :dependent => :delete_all

  # after user post
  def self.create_new(probe, dst)
      tr = self.new
      tr.probe = probe
      tr.dst = dst
      tr.submitted = false
      tr.available = false
      tr.failed = false
      tr.uuid = SecureRandom.uuid
      tr.save
      tr
  end

  def submit
    api = API.new
    begin
      self.msm_id = api.submit(self.probe, self.dst)
      self.submitted = true
      puts self.msm_id
    rescue Exception => exc
      self.failed = true
      puts exc.message
    end
    self.save
  end

  def fetch
    api = API.new
    begin
      resp = api.fetch_result(self.msm_id) # resp of Ripe is an array
      return if resp.length == 0 # result not available, do nothing
      resp = resp.first
      self.dst_addr = resp['dst_addr']
      self.endtime = Time.at(resp['endtime'])
      self.src = resp['src_addr']

      resp['result'].each do |r|
        hop = self.hops.create(:no => r['hop'])
        packet = r['result'].first
        hop.from = packet['from']
        hop.rtt = packet['rtt'] unless hop.from == '*'
        hop.save
      end

      self.available = true
      puts "available"
    rescue Exception => exc
      self.failed = true
      self.hops.destroy_all
      puts exc.message
    end
    self.save
  end

  def mark_failed
    self.failed = true
    self.save
  end

  def to_list
    # make the source(probe) itself the first point
    gtr_list = Array.new

    gtr_list = [gtr_fill(0, self.src, 0)] if self.available

    self.hops.each do |hop|
      begin
        gtr_list << gtr_fill(hop.no, hop.from, hop.rtt)
      rescue Exception => exc
        puts exc.message
        return []
      end
    end

    return gtr_list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController
  include Ipv4
  include Ripe

  def ip
    if params[:ip]
      begin
        @ip = params[:ip]
        @city = GEO.city(params[:ip])
        @asn = ASN.asn(params[:ip])
      rescue Exception => exc
        @msg = "#{exc.message}"
      end
    end
  end

  def check
    #if !request.post?
    #  render :json => {
    #    :code => '-1',
    #    :msg => 'method not allowed',
    #  }
    #end
    @tr = Traceroute.find_by(uuid: params[:uuid])
    if @tr.nil?
      render :json => {
        :code => '-1',
        :msg => 'traceroute not found',
      }
      return
    end

    if @tr.failed?
      render :json => {
        :code => '-1',
        :msg => 'traceroute failed, please check your destination',
      }
      return
    end

    if @tr.available?
      render :json => {
        :code => '1',
        :msg => '',
      }
    else
      render :json => {
        :code => '0',
        :msg => '',
      }
    end
    return

  end

  def index
    @gtr_list = []
    @gtr_list_skip = []
    @gtr_list_as = []

    if request.post? && params[:paste]
      @paste = params[:paste]
      @gtr_list = plain_to_list(@paste)
      if @gtr_list.empty?
        @paste_msg = "bad traceroute format"
        return
      end
      @gtr_list_skip = skipfy(@gtr_list)
      @gtr_list_as = strip_by_as(@gtr_list)

=begin
      @hash = Gmaps4rails.build_markers(@gtr_list) do |gtr, marker|
        marker.lat(gtr[:lat])
        marker.lng(gtr[:lng])
        marker.picture({
          "url" => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=#{gtr[:id]}|FE6256|000000",
          "width" => 21,
          "height" => 34,
        })
      end
=end
      return
    end

    if request.post? && params[:dst]
      # limit the requests per minute by IP address
      count = Rails.cache.increment(request.remote_ip, 1, :expires_in => 600)
      puts count
      if count > REQS_LIMIT
        @alert_msg = "You submit too frequently. Please try later."
        return
      end
          
      @tr = Traceroute.create_new(params[:probe], params[:dst])
      redirect_to "/traceroute/#{@tr.uuid}/"
      return
    end

    if params[:uuid]
      @tr = Traceroute.find_by(uuid: params[:uuid])

      unless @tr.nil?
        @gtr_list = @tr.to_list
        if (@gtr_list.length > 0)
          @gtr_list_skip = skipfy(@gtr_list)
          @gtr_list_as = strip_by_as(@gtr_list)
        end
      end
      return
    end

    probes = Rails.cache.fetch(:probes, :expires_in => 1800) do
      api = API.new
      api.fetch_probes()
    end

    # options for select form
    @probes_options = Hash.new
    probes.each do |p|
      @probes_options[p['name']] = p['id']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title GTR
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    div class="navbar navbar-inverse navbar-fixed-top" role="navigation"
      div class="container"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
          a class="navbar-brand" href="#" GTR
        div class="collapse navbar-collapse"
          ul class="nav navbar-nav"
            li
              = active_link_to 'Home', root_path, :wrap_tag => :li, :active => :exclusive
            li
              = active_link_to 'IP Lookup', ip_path, :wrap_tag => :li

    div class="container"
      == yield

    == yield :js
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/lookup/index.html.slim
- content_for :js do
  = javascript_include_tag "//maps.googleapis.com/maps/api/js?key=AIzaSyCeAMC0llHnCIdI9YLNKrP6Y2yWCyKiCAM&sensor=false"

h1 Global Visual Traceroute
div class="row"
  div class="col-md-9 left"
    div id="map-canvas"
    hr
    div
      = form_tag(root_path) do
        div class=["form-group", ("has-error has-feedback" unless @paste_msg.nil?)]
          = label_tag :paste, 'Paste your Traceroute output'
          = text_area_tag :paste, @paste, rows: 2, class: 'form-control'
          - unless @paste_msg.nil?
            span class="glyphicon glyphicon-remove form-control-feedback"
        = submit_tag('Draw', :class => 'btn btn-default')
        button type="button" class="btn btn-link" id="paste-reset" Clear
        span style="float: right" = @paste_msg

  div class="col-md-3 right"
    - unless @probes_options.nil?
      div
        = form_tag(root_path) do
          div class=["form-group"]
            = label_tag :probe, 'Source'
            = select_tag :probe, options_for_select(@probes_options)
          div class=["form-group"]
            = label_tag :dst, 'Destination'
            = text_field_tag :dst, nil, class: 'form-control', placeholder: 'IP / Hostname'
          = submit_tag('Submit', :class => 'btn btn-default')

    - unless @tr.nil?

      div id="result"
        - if @tr.failed
          p 
            | Traceroute failed, please check your destination and re-submit.
        - else
          div
            | Save this 
            a href="/traceroute/#{@tr.uuid}/"
              | Permanent link 

          - if @tr.available
            p 
              | Src: #{@tr.src}
              br
              | Dst: #{@tr.dst} (#{@tr.dst_addr})

        div id="load" style="display: none"
          = image_tag('spinner.gif', size: '25', id: "loading")
          
    - if !@gtr_list.nil? && @gtr_list.any?
      ul id="tab-head" class="nav nav-pills"
        li class="active"
          a href="#org-tab" data-toggle="pill" Original
        li
          a href="#asn-tab" data-toggle="pill" AS only

      div class="tab-content"
        div id="org-tab" class="tab-pane fade in active"
          table class="table table-condensed table-hover"
            - for gtr in @gtr_list
              tr class=[("has-marker" unless gtr[:lat] == 'n/a')] data="#{gtr[:id]}"
                td
                  = gtr[:id]
                td
                  - if gtr[:info] != 'n/a'
                    a class="ip-pop" data-container="body" data-toggle="popover" data-placement="left" data-content="#{gtr[:info]}"
                      = gtr[:ip]
                  - else
                    = gtr[:ip]
                td = gtr[:cc]
                td = gtr[:asn]
                td = gtr[:rtt]
        div id="asn-tab" class="tab-pane fade"
          table class="table table-condensed table-hover"
            - for gtr in @gtr_list_as
              tr
                td = gtr[:id]
                - if gtr[:asn].start_with?('AS')
                  td = gtr[:asn]
                  td = gtr[:cc]
                  td = gtr[:as]
                - else
                  td = gtr[:ip]
                  td = gtr[:cc]
                  td

- unless @alert_msg.nil?
  javascript:
    alert('#{@alert_msg}')

javascript:
  var gtr_list_org = #{raw @gtr_list.to_json};
  var gtr_list_skip = #{raw @gtr_list_skip.to_json};
  var gtr_list = gtr_list_org;
  var avail;

- unless @tr.nil?
  javascript:
    var avail = #{@tr.available};
    var uuid = "#{@tr.uuid}";
    var failed = #{@tr.failed};

app/views/lookup/ip.html.slim
h1 IP Lookup
p
  = form_tag(ip_path) do
    = label_tag(:ip, "IPv4 address")
    = text_field_tag(:ip, @ip)
    = submit_tag("Lookup")

- unless @msg.nil?
    div class="alert alert-warning alert-dismissable"
      button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
      = @msg

p
  = @city unless @city.nil?

p
  = @asn unless @asn.nil?